version: '3.7'

services:
  backend:
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
    #build: backend/.
    image: remilecodeur/tp1-backend:latest
    container_name: javaBackendApi
    networks:
      - app-network
    depends_on:
      - database
      - httpd

  database:
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
    #build: Database/.
    image: remilecodeur/tp1-database:latest
    container_name: databaseTP1
    networks:
      - app-network

  httpd:
    ports:
      - "80:80"
    #build: webserver/.
    image: remilecodeur/tp1-httpd:latest
    container_name: webserver
    networks:
      - app-network

  front:
    ports:
      - "8070:8070"
    image: remilecodeur/front-devops:latest
    container_name: front
    networks:
      - app-network

networks:
  app-network:
