---
- name: Launch backend container
  docker_container:
    name: javaBackendApi
    image: remilecodeur/tp1-backend:1.0
    state: started
    networks:
      - name: app-network
    env:
      POSTGRES_DB: "{{ POSTGRES_DB }}"
      POSTGRES_USER: "{{ POSTGRES_USER }}"
      POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"