all:
  # Définit des variables qui s'appliquent à tous les hôtes
 vars:
  ansible_user: centos
  ansible_ssh_private_key_file: ~/.ssh/remi.louedec
  POSTGRES_DB: db
  POSTGRES_USER: usr
  POSTGRES_PASSWORD: pwd
  postgres_hostname: databaseTP1
  network: app-network

 children:
   prod:
      # Définit les hôtes
     hosts: remi.louedec.takima.cloud