---
- name: Launch database container
  docker_container:
    name: databaseTP1
    image: remilecodeur/tp1-database:latest
    state: started
    networks:
      - name: app-network
    env:
      POSTGRES_DB: "{{ POSTGRES_DB }}"
      POSTGRES_USER: "{{ POSTGRES_USER }}"
      POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"