---
- name: Launch database container
  docker_container:
    name: "{{ postgres_hostname }}"
    image: remilecodeur/tp1-database:1.0
    state: started
    networks:
      - name: "{{ network }}"
    env:
      POSTGRES_DB: "{{ POSTGRES_DB }}"
      POSTGRES_USER: "{{ POSTGRES_USER }}"
      POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"